### ISSUE TITLE
One last thing(maybe)

### ISSUE THREAD

**Issue by EricJeffrey** [EricJeffrey/TheCheatSheet#10]
1. Make ways to export data from db
2. Add code segments that we already have to database

I will think about these stuff later, it won't be hard, but surely annoying

**Comment by EricJeffrey** [comment]
![image](https://user-images.githubusercontent.com/33823695/97805504-89a41680-1c91-11eb-9bf1-f10c0455b4e0.png)


add those stuff to it, and I just find that `html` and `regular expression` tag were forgotten, anyway they can be `TEXT`

**Comment by 1dooooo** [comment]
well done ！
