### ISSUE TITLE
接口 - 获取所有语言

### ISSUE THREAD

**Issue by EricJeffrey** [EricJeffrey/TheCheatSheet#3]
添加一个用于获取所有代码段语言类型的列表。
如下图左侧所示，因为需要按照语言类型检索，因此需要一个获取所有语言类型的接口。只返回已收录的语言类型。

![img](https://user-images.githubusercontent.com/33823695/96879580-cc563980-14ae-11eb-9560-3c940f38192f.png)

接口说明

-  `/codeseg/alllang`, `GET`, 获取所有代码段语言类型，返回为Json数组，如下：
   ```json
   [
       "Java",
       "C++",
       ...
   ]
   ```

**Comment by EricJeffrey** [comment]
@1dooooo 你怎么看？

**Comment by 1dooooo** [comment]
nice

**Comment by 1dooooo** [comment]
请使用驼峰或者下划线命名

**Comment by EricJeffrey** [comment]
😂 OK，所以改成 `/codeseg/allLang` ?

**Comment by 1dooooo** [comment]
/codeseg/allTags   **maybe** ok
[https://translate.google.cn/#view=home&op=translate&sl=en&tl=zh-CN&text=tags](url)

**Comment by 1dooooo** [comment]
/codeSeg/allTags  more

**Comment by EricJeffrey** [comment]
Then we are mixing `tag` with `language`, which will bring inconsistency.

**Comment by EricJeffrey** [comment]
Maybe we should change `language` into `tag`?

**Comment by 1dooooo** [comment]
> Then we are mixing `tag` with 'language`, which will bring inconsistency.

you are right! `toEnglish("缩写")` is deprecated，inconsistency too.

**Comment by EricJeffrey** [comment]
??? I'm tight? 
back to the problem, `/codeseg/allLanguages` ?

**Comment by 1dooooo** [comment]
ok
